[package]
name = "rnaapi_derive"
version = "1.0.0"
edition = "2024"
description = "Derive crate for building get endpoints"
license = "GPL-3.0-only"

[dependencies]
deluxe = "0.5.0"
proc-macro2 = "1.0.106"
quote = "1.0.44"
syn = "2.0.114"

[lib]
proc-macro = true
